[supabase]
url = "https://lumzhvjmbppdbidkweea.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1bXpodmptYnBwZGJpZGt3ZWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MjM3NzYsImV4cCI6MjA3OTQ5OTc3Nn0.yQnDNg7TuQhWjTMAni5ZJupsJq-PgsVKkVNMHRhfqwE"